apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-1
#   labels:
#     env: Test
# spec:
#   containers:
#     name: nginx
#      image:  nginx




