apiVersion: v1
kind: Service
metadata:
    name: myapp-service
spec:
    type: NodePort
    ports:
    - name:  Ben Port
      port:  80
      nodePort: 30005
      protocol: TCP
    selector:
       app: myapp