apiVersion: apps/v1
kind: ReplicaSets
metadata:
  name: myapp-replica
  labels:
    app: nginx-dev-pod 
spec:
  selector:
    matchlabels:
       app: nginx-dev-pod
  replicas: 3
  template:
    metadata:
  name: nginx-dev-pod
  labels:
    app: nginx-dev-pod
    spec:
  containers:
    name:  nginx-container
    image:  nginx:latest

